/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.DangKyController;

/**
 *
 * @author Nguyen Nam Lam
 */
public class DangKyUI extends javax.swing.JFrame {

    /**
     * Creates new form StrudentsManager
     */
    public DangKyUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        DangKyController evt = new DangKyController(this);
        evt.init();
        btnAdd.addActionListener(evt);
        btnUpdate.addActionListener(evt);
        btnDel.addActionListener(evt);
        btnSearch.addActionListener(evt);
        btnSort.addActionListener(evt);
        btnReset.addActionListener(evt);
        jTable.addMouseListener(evt);
        jTable.addKeyListener(evt);
        rbMale.addActionListener(evt);
        rbFemale.addActionListener(evt);
        jCheckBoxDatPhong.addActionListener(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGender = new javax.swing.ButtonGroup();
        buttonSorted = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txttinh = new javax.swing.JTextField();
        txthuyen = new javax.swing.JTextField();
        txtxa = new javax.swing.JTextField();
        jcbRoom = new javax.swing.JComboBox<>();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        txtdd = new javax.swing.JTextField();
        txtmm = new javax.swing.JTextField();
        txtyyyy = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBoxDatCoc = new javax.swing.JCheckBox();
        jCheckBoxDatPhong = new javax.swing.JCheckBox();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnSort = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký");
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd.setText("Đăng ký");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        buttonSorted.add(btnReset);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã sinh viên:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Giới tính:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ngày sinh:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tên sinh viên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quê quán:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Xã:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Huyện:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Tỉnh:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText(" ĐĂNG KÝ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        txtId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 220, -1));

        txttinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txttinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 120, -1));

        txthuyen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txthuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 120, -1));

        txtxa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, -1));

        jcbRoom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(jcbRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        btGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbMale.setText("Nam");
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        btGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbFemale.setText("Nữ");
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        txtdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 30, -1));

        txtmm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 30, -1));

        txtyyyy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtyyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, -1));

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 170, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("/");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("/");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jCheckBoxDatCoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxDatCoc.setText("Đặt cọc");
        getContentPane().add(jCheckBoxDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jCheckBoxDatPhong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxDatPhong.setText("Đặt phòng");
        getContentPane().add(jCheckBoxDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MÃ SINH VIÊN", "TÊN SINH VIÊN", "GIỚI TÍNH", "NGÀY SINH", "QUÊ QUÁN", "SĐT", "ĐẶT CỌC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTable.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(45);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(35);
            jTable.getColumnModel().getColumn(6).setPreferredWidth(35);
            jTable.getColumnModel().getColumn(7).setPreferredWidth(45);
        }

        getContentPane().add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 740, 110));

        btnSort.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSort.setText("Sắp xếp");
        getContentPane().add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        btnDel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDel.setText("Xoá");
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearch.setText("Tìm");
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Sửa");
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DangKyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DangKyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DangKyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DangKyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new DangKyUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGender;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDel;
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnSort;
    public javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonSorted;
    public javax.swing.JCheckBox jCheckBoxDatCoc;
    public javax.swing.JCheckBox jCheckBoxDatPhong;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPaneTable;
    public javax.swing.JTable jTable;
    public javax.swing.JComboBox<String> jcbRoom;
    public javax.swing.JRadioButton rbFemale;
    public javax.swing.JRadioButton rbMale;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPhone;
    public javax.swing.JTextField txtdd;
    public javax.swing.JTextField txthuyen;
    public javax.swing.JTextField txtmm;
    public javax.swing.JTextField txttinh;
    public javax.swing.JTextField txtxa;
    public javax.swing.JTextField txtyyyy;
    // End of variables declaration//GEN-END:variables
}
