/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controllers.EvenPheDuyet;



/**
 *
 * @author Admin
 */
public class PheduyetUI extends javax.swing.JFrame {

    private DefaultTableModel model;
    private EvenPheDuyet even;
    private boolean clickRow = false;
    private int selectRow;
  
    
    public PheduyetUI() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) table.getModel();
        even = new EvenPheDuyet();
        even.updateTable(model);
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        gerder = new javax.swing.JLabel();
        phoneNumber1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("phê duyệt");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã sinh viên:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Giới tính:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ngày sinh:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tên sinh viên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quê quán:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Phê duyệt");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Chọn phòng");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MÃ SINH VIÊN", "TÊN SINH VIÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐỊA CHỈ", "SĐT", "PHÒNG", "Đặt cọc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPaneTable.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(40);
            table.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        getContentPane().add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 770, 150));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Phê duyệt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Không phê duyệt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name.setText("____________________________");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        address.setText("____________________________");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id.setText("____________________________");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("____________________________");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        birthday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        birthday.setText("____________________________");
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        gerder.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gerder.setText("_________");
        getContentPane().add(gerder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, -1));

        phoneNumber1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneNumber1.setText("____________________________");
        getContentPane().add(phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!clickRow)
            JOptionPane.showMessageDialog(null, "Chưa chọn đơn", "Lôi", JOptionPane.ERROR_MESSAGE);
        else{
            try{
                if(even.pheduyet(selectRow, jComboBox1.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null, "Phê duyệt thành công");
                even.updateTable(model);
                }
                    else JOptionPane.showMessageDialog(null, "Phê duyệt không thành công", "Lôi", JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception ex){
                if(ex.equals("Tồn tại"))
                    JOptionPane.showMessageDialog(null, "Sinh viên này đã được duyệt", "Lôi", JOptionPane.ERROR_MESSAGE);
                else JOptionPane.showMessageDialog(null, "Phòng đã đầy", "Lôi", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!clickRow)
            JOptionPane.showMessageDialog(null, "Chưa chọn đơn", "Lôi", JOptionPane.ERROR_MESSAGE);
        else{
            LidoUI lido = new LidoUI(Integer.parseInt(table.getValueAt(selectRow, 1).toString()));
            lido.setVisible(rootPaneCheckingEnabled);
            lido.setDefaultCloseOperation(HIDE_ON_CLOSE);
            even.updateTable(model);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        selectRow = table.getSelectedRow();
        if(selectRow != -1){
            clickRow = true;
            id.setText(table.getValueAt(selectRow, 1).toString());
            name.setText(table.getValueAt(selectRow, 2).toString());
            gerder.setText(table.getValueAt(selectRow, 3).toString());
            birthday.setText(table.getValueAt(selectRow, 4).toString());
            address.setText(table.getValueAt(selectRow, 5).toString());
            phoneNumber1.setText(table.getValueAt(selectRow, 6).toString());
            String s = table.getValueAt(selectRow, 7).toString();
            if(!s.equals("0")){
                jComboBox1.removeAllItems();
                jComboBox1.addItem(s);
            }
            else
                even.updateComboBox(jComboBox1, s);
        }
    }//GEN-LAST:event_tableMouseClicked

//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PheduyetUI().setVisible(true);
//            }
//        });
//    }
    
//    public void resetText(){
//        numberRoom.setText("");
//        building.setText("");
//        maxSV.setText("");
//        typeRoom.setText("............");
//        numberStudents.setText("...........");
//    }
    
//    private void setRowColor(JTable table, int rowIndex, Color color) {
//        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
//                                                           boolean hasFocus, int row, int column) {
//                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
//                if (row == rowIndex) {
//                    c.setBackground(color);
//                } else {
//                    c.setBackground(table.getBackground());
//                }
//
//                return c;
//            }
//        });
//        table.repaint();
//    }
    
//    public String getNumbeRoom(){
//        return roomTable.getValueAt(selectRow, 1).toString();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel gerder;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneNumber1;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
