/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.EvenThongKe;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKe extends javax.swing.JFrame {
    private EvenThongKe even;
    private DefaultTableModel model;
    private int selectRow;
    private boolean clickRow = false;
   
    public ThongKe() {
        initComponents();
        model = (DefaultTableModel) jTable.getModel();
        even = new EvenThongKe();
        even.updateTable(model);
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Đang xét");
        jComboBox1.addItem("Thành công");
        jComboBox1.addItem("Hủy");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        gerden = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        phonenumber = new javax.swing.JLabel();
        nameroom = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý đăng ký");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loc.setText("Lọc");
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã sinh viên:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Giới tính:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ngày sinh:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tên sinh viên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quê quán:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Thống kê");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Phòng");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MÃ SINH VIÊN", "TÊN SINH VIÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐỊA CHỈ", "SĐT", "PHÒNG", "Đặt cọc", "Trang thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPaneTable.setViewportView(jTable);

        getContentPane().add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 740, 220));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        name.setText(".......................");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 110, -1));

        gerden.setText("...................");
        getContentPane().add(gerden, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        birthday.setText(".......................");
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));

        phonenumber.setText(".......................");
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 140, -1));

        nameroom.setText(".......................");
        getContentPane().add(nameroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 140, 20));

        address.setText(".......................");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 250, -1));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        String s = jComboBox1.getSelectedItem().toString();
        if(even.clickLoc(s))
            even.updateTable(model);
        else JOptionPane.showMessageDialog(null, "Không tìm thấy đơn cần lọc");
    }//GEN-LAST:event_locActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(id.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Mã sinh viên không được để trống");
        else{
            try{
                int i = Integer.parseInt(id.getText());
                if(even.findSV(i))
                    even.updateTable(model);
                else JOptionPane.showMessageDialog(null, "Không tim thấy");
            } catch(Exception ex){
                JOptionPane.showMessageDialog(null, "mã sinh viên chỉ gồm các chứ số và nhỏ hơn 3*10^10 chứ số");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        even.reset();
        even.updateTable(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        selectRow = jTable.getSelectedRow();
        if(selectRow != -1){
            clickRow = true;
            id.setText(jTable.getValueAt(selectRow, 1).toString());
            name.setText(jTable.getValueAt(selectRow, 2).toString());
            gerden.setText(jTable.getValueAt(selectRow, 3).toString());
            birthday.setText(jTable.getValueAt(selectRow, 4).toString());
            address.setText(jTable.getValueAt(selectRow, 5).toString());
            phonenumber.setText(jTable.getValueAt(selectRow, 6).toString());
            nameroom.setText(jTable.getValueAt(selectRow, 7).toString());

        }
    }//GEN-LAST:event_jTableMouseClicked
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PheduyetUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel gerden;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPaneTable;
    public javax.swing.JTable jTable;
    public javax.swing.JButton loc;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameroom;
    private javax.swing.JLabel phonenumber;
    // End of variables declaration//GEN-END:variables
}
